# Generated by Django 5.2.1 on 2025-06-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='desc',
            field=models.CharField(default='No description', max_length=100),
        ),
        migrations.AddField(
            model_name='carlist',
            name='name',
            field=models.CharField(default='Unnamed', max_length=50),
        ),
    ]
