# Generated by Django 5.2.1 on 2025-06-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_carlist_desc_carlist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlist',
            name='active',
        ),
        migrations.AddField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carlist',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
